### ISSUE TITLE
[Suggestion| Feature request] Add the ability to generate a blueprint file from the command line

### ISSUE THREAD

**Issue by paulmassen** [getgrav/grav-plugin-devtools#15]
Hi,

I thought it would be a nice addition to allow the user to generate some grav-specific files frome the command line.

Most of the time, I copy paste these blueprints as I can not remember it or because these files are very indentation-sensitive.

Here are some files I have to write on almost all my projects and that could be useful in my opinion:

## New tab in blueprint

```
title: Item
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      fields:
        blog:
          type: tab
          title: MYNEWTAB
          
          fields:
            header.mytextfield:

```
### Append content to the first Tab
```
title: Gallery
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        content:
          fields:
            header.an_example_text_field:
              type: text
              label: Add a number
              default: 5
              validate:
                required: true
                type: int

```
### Prepend content to the first tab
```
title: Image Accueil
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        content:
          fields:
            header.an_example_text_field:
              ordering@: 0
              type: text
              label: Add a number
              default: 5
              validate:
                required: true
                type: int

```

## Modular pages:
```
{% extends 'partials/base.html.twig' %}
{% block content %}
{{ page.content }}
    {% for module in page.collection() %}
        {{ module.content }}
    {% endfor %}
{% endblock %}
```

There might be some other useful files. 
Let me know your thoughts!
