### ISSUE TITLE
github names with capitals in them get - added in them

### ISSUE THREAD

**Issue by AEnterprise** [getgrav/grav-plugin-devtools#40]
github usernames in urls are case-insensitive, but when you enter them with capitals in the new-plugin command they get lowercased and - gets added

so AEnterprise becomes a-enterprise

**Comment by rhukster** [comment]
Just tested with:

```
 $ bin/plugin devtools newplugin                                                                              [11:17:28]
Enter Plugin Name: My Plugin
Enter Plugin Description: none
Enter Developer Name: A Enterprises
Enter GitHub ID (can be blank): AEnterprises
Enter Developer Email: email@aenterprises.com
```

Resulting blueprint:

```
name: My Plugin
version: 0.1.0
description: none
icon: plug
author:
  name: A Enterprises
  email: email@aenterprises.com
homepage: https://github.com/AEnterprises/grav-plugin-my-plugin
demo: http://demo.yoursite.com
keywords: grav, plugin, etc
bugs: https://github.com/AEnterprises/grav-plugin-my-plugin/issues
docs: https://github.com/AEnterprises/grav-plugin-my-plugin/blob/develop/README.md
license: MIT
```

However, if you don't provide a `GitHub ID`, it will fallback and hyphenize the name provided, so maybe that is what you are seeing.
