### ISSUE TITLE
Theme inheritance. Problem with apostrophe and quotes.

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav-plugin-devtools#76]
Tried to inherit Typhoon theme and got an error:
```php
TypeError
Argument 1 passed to Mexitek\PHPColors\Color::__construct() must be of the type string, null given, 
called in /Users/artyom/domains/mydomain/user/plugins/color-tools/color-tools.php on line 65

/**
     * Instantiates the class with a HEX value
     * @param string $hex
     * @throws Exception
     */
    public function __construct(string $hex). <---- this line
    {
        $color = self::sanitizeHex($hex);
        $this->_hex = $color;
        $this->_hsl = self::hexToHsl($color);
        $this->_rgb = self::hexToRgb($color);
    }

```

Console:
```yaml
➜  mydomain bin/plugin devtools new-theme

 Enter Theme Name:
 > My Typhoon

 Enter Theme Description:
 > Customizing Typhoon

 Enter Developer Name:
 > Artyom Mezin

 Enter GitHub ID (can be blank):
 > 7556290

 Enter Developer Email:
 > my@mail.site

 Please choose an option:
  [pure-blank ] Basic Theme using Pure.css
  [tailwind   ] Basic Theme using tailwind.css
  [inheritance] Inherit from another theme
  [copy       ] Copy another theme
 > inheritance

 Please choose a theme to extend:
  [0] quark
  [1] typhoon
 > 1


SUCCESS theme My Typhoon -> Created Successfully

Path: /Users/artyom/domains/mydomain/user/themes/my-typhoon
```

Ok. Cache cleared, browser refreshed, error still exist... found another issue: https://github.com/getgrav/grav/issues/3549

Decided to compare `typhoon.yaml` and `my-typhoon.yaml` to find differences and that's it:
![image](https://user-images.githubusercontent.com/7556290/178718572-8afd05a7-d560-4daf-8045-74ae390bb2a7.png)

Normal `typhoon.yaml` color block:
```yaml

colors:                                                             # Doesn't work for modular as the CSS is page-level
  text_style: 'text-gray-600 dark:text-gray-400'                    # Text color (Any valid Tailwind color)
  brightness_lighter: '20'                                          # The percentage amount brighter for *-primary-lighter colors
  brightness_darker: '20'                                           # The percentage amount darker for *-primary-darker colors
  primary: '#3893F8'                                                # The primary accent color used throughout the page (Any valid Tailwind color)
```

Bad `my-typhoon.yaml` color block:
```yaml

colors:                                                             # Doesn&#039;t work for modular as the CSS is page-level
  text_style: &#039;text-gray-600 dark:text-gray-400&#039;                    # Text color (Any valid Tailwind color)
  brightness_lighter: &#039;20&#039;                                          # The percentage amount brighter for *-primary-lighter colors
  brightness_darker: &#039;20&#039;                                           # The percentage amount darker for *-primary-darker colors
  primary: &#039;#3893F8&#039;                                                # The primary accent color used throughout the page (Any valid Tailwind color)
```

Why does it use `&#039;` istead of `'`?

Same about quotes:
![image](https://user-images.githubusercontent.com/7556290/178719584-8ea41cf0-133e-4221-99aa-19843c5c742b.png)

`&quot;` istead of `"`
